on: pull_request

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to comment hello
    steps:
    - name: Hello world action step
      id: hello
      uses: HarishTeens/woofy@v2.3
      with:
        who-to-greet: 'Mona the Octocat'
    - name: Checkout
      uses: HarishTeens/woofy@v2.3

    - name: Comment PR
      uses: HarishTeens/woofy@master
      with:
        message: 'Hello ${{ steps.hello.outputs.name }}'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
